### ISSUE TITLE
Feedback about complex filters performance (filter speed)

### ISSUE THREAD

**Issue by ThiloteE** [Betterbird/thunderbird-patches#141] opened 2023-04-15 20:52 UTC
I wonder if you all have similar experiences. As I have not completely managed to isolate specific triggers just yet, this probably is more feedback than an actual bug report.

## Issue:

Main issue:

- Messages are moved to subfolders very slowly, if multiple messages arrive at the same time, e.g. after starting Betterbird.
- In some circumstances, I can see delay of up to roughly \~ 3 seconds per message. When there is 30 messages, I will have to wait like a minute for it all to be sorted.

Further info:

- While filters run, the main window is very slow to respond. E.g. clicking on a message or folder will have long response time.
- While I have multiple mail-accounts and rss feeds with some complex filters, it currently only noticeably affects a particular mail-account

### How **not** to trigger slowness:

- When I receive only one message at a time, I feel like there is only marginal delay.

## How to reproduce:

I have not yet identified a specific trigger.

## My filterrules.dat

[slowness-msgFilterRules.txt](https://github.com/Betterbird/thunderbird-patches/files/11240615/slowness-msgFilterRules.txt)

Be aware, there are filters in there, which are disabled.

###  Folders that experience most slowdown:

- Some, maybe all, folders related to "AAA". In particular the following two:
- `imap://my.mail.account%40posteo.de@posteo.de/INBOX/Tools/AAA/1-AAA-to-Thilo`
- `imap://my.mail.account%40posteo.de@posteo.de/INBOX/Tools/AAA/2-DailyMessages`

**Comment by ThiloteE** [comment] 2023-04-15 20:55
The behaviour is triggered as soon as two messages arrive at the same time into the DailyMessages folder. There is notable lag.

**Comment by ThiloteE** [comment] 2023-04-15 21:19
Both quality and integrity are fine IMHO. I think quality might be prefered, but not sure if worth the effort to rename all dialogues and the documentation :D

[integrity](https://en.wikipedia.org/wiki/Integrity):

> Integrity is the practice of being honest and showing a consistent and uncompromising adherence to strong moral and ethical [principles](https://en.wikipedia.org/wiki/Principles) and [values](https://en.wikipedia.org/wiki/Values).[[1]](https://en.wikipedia.org/wiki/Integrity#cite_note-oxford-1)[[2]](https://en.wikipedia.org/wiki/Integrity#cite_note-2)[[3]](https://en.wikipedia.org/wiki/Integrity#cite_note-3) In [ethics](https://en.wikipedia.org/wiki/Ethics), integrity is regarded as the honesty and [truthfulness](https://en.wikipedia.org/wiki/Honesty) or [accuracy](https://en.wikipedia.org/wiki/Accuracy) of one's actions. Integrity can stand in opposition to [hypocrisy](https://en.wikipedia.org/wiki/Hypocrisy),[[4]](https://en.wikipedia.org/wiki/Integrity#cite_note-4) in that judging with the standards of integrity involves regarding **internal consistency** as a virtue, and suggests that parties holding within themselves apparently conflicting values should account for the discrepancy or alter their beliefs. The word integrity evolved from the Latin adjective [integer](https://en.wiktionary.org/wiki/integer#Latin), meaning whole or complete.[[1]](https://en.wikipedia.org/wiki/Integrity#cite_note-oxford-1) In this context, integrity is the inner sense of "wholeness" deriving from qualities such as [honesty](https://en.wikipedia.org/wiki/Honesty) and consistency of [character](https://en.wikipedia.org/wiki/Moral_character).[[5]](https://en.wikipedia.org/wiki/Integrity#cite_note-5)

In JabRefs context, integrity would be about "consistency" or "internal consistency".

[Quality](https://en.wikipedia.org/wiki/Quality_(philosophy))

> A quality is an attribute or a [property](https://en.wikipedia.org/wiki/Property_(philosophy)) characteristic of an [object](https://en.wikipedia.org/wiki/Object_(philosophy)) in [philosophy](https://en.wikipedia.org/wiki/Philosophy).[[1]](https://en.wikipedia.org/wiki/Quality_(philosophy)#cite_note-Cargile,_1995-1) In [contemporary philosophy](https://en.wikipedia.org/wiki/Contemporary_philosophy) the [idea](https://en.wikipedia.org/wiki/Idea) of qualities, and especially how to distinguish certain kinds of qualities from one another, remains controversial.[[1]](https://en.wikipedia.org/wiki/Quality_(philosophy)#cite_note-Cargile,_1995-1).

> Quality (Latin: quality, characteristic, property, condition) has three meanings:
> 
> a) neutral: the sum of all properties of an object, system or process
> b) evaluates: the quality of all properties of an object, system or process
> c) evaluates: the individual values preceding the action and its results With regard to points a) and b),

**Comment by Betterbird** [comment] 2023-04-15 22:20
> While I have multiple mail-accounts and rss feeds with some complex filters, it currently only noticeably affects a particular mail-account

I think this has nothing to do with Betterbird or complex filters, it's more likely that there is some delay caused by a certain IMAP account and moving messages. You could even try moving messages manually.

You should try this with TB and a simple filter to see what happens. You can also run this with logging (https://wiki.mozilla.org/MailNews:Logging), both IMAP and Filters logging to see where the time is spent.

If it's slow in TB alone, you can file a bug at TB's Buzilla.

I'm closing this since right now there is nothing I can action here.

**Closed by Betterbird** 2023-04-15 22:20 UTC

**Comment by ThiloteE** [comment] 2023-06-22 21:25
Since I installed BB 102.12, all is fine. I am not sure if my mail provider coincidentially transitioned to better hardware or if it's TB / BB code or if changing something in my filterrules caused this happy occurence. If I find the time, I will try to find the root cause, but since everything is working fine now, my motivation for this additional adventure is low.

**Comment by Betterbird** [comment] 2023-06-22 21:30
Nothing changed in TB/BB.
