### ISSUE TITLE
Search folder for RSS feeds not updating consistently

### ISSUE THREAD

**Issue by cybrkyd** [Betterbird/thunderbird-patches#372] opened 2024-11-23 13:11 UTC
When using a search folder to draw from multiple RSS feeds, the search folder is not updating consistently.

Issue:
-- 4 RSS feeds from different sources
-- One search folder used to combine the four RSS feeds
-- When the feeds are refreshed and new messages pulled, the search folder does not show all the messages sometimes. This is easily seen by the message count difference.
-- Navigating out of the search folder and returning sometimes refreshes the results, sometimes not.

This appears to be a cache issue but I'm not sure. Also, this behaviour is not present in Thunderbird, only in Betterbird.

**Comment by Betterbird** [comment] 2024-11-23 13:26
Yes, this behavior is not present in TB since TB only uses the cache to 
pre-fill the view and then runs the search anyway. Take a look at Issue 
#368. If you're on the "latest build" version for either 115 or 128, you 
can set pref mailnews.virtual_folders.verbose to see more details. In 
Issue #368 there is also a special build for 115 with even more logging.

Your cooperation would be appreciated to track down the missing messages.

**Comment by Betterbird** [comment] 2024-11-23 13:44
Can you attach a screenshot that shows the wong counts.

Also, navigation from and to the search folder shouldn't refresh the count since the folder is restored from the cache. It only refreshes when you press the "update" button on the search properties panel. Check the logging, it's pretty obvious.

**Comment by cybrkyd** [comment] 2024-11-23 16:54
Running BB to attempt to reproduce. On latest RSS download, the following error was noted repeatedly at each get request:

gloda.datastore: got error in _asyncTrackerListener.handleError(): 19: constraint failed 5 GlodaDatastore.jsm:1891:27
    handleError resource:///modules/gloda/GlodaDatastore.jsm:1891

It may be nothing to do with this.

Quiet on my feeds over the weekend so not yet able to reproduce and take screens. I'm watching and will post as soon as I see it.

**Comment by Betterbird** [comment] 2024-11-23 21:58
Please read
https://github.com/Betterbird/thunderbird-patches/issues/368#issuecomment-2495576622
We've see a drop. We're using a version now with heaps of logging, so it should become apparent where the messages get lost.

**Comment by Betterbird** [comment] 2024-11-23 23:48
It's a duplicate of Issue #368, we'll fix it there. New binaries will be available soon.

**Closed by Betterbird** 2024-11-23 23:48 UTC

**Comment by Betterbird** [comment] 2024-11-25 11:30
We've made some progress, please read https://github.com/Betterbird/thunderbird-patches/issues/368#issuecomment-2497742947. TL;DR: Repair the feed folders which contribute to the virtual folder. Do you know that you can add multiple subscriptions to a folder, so you don't need the virtual folder:
https://support.mozilla.org/en-US/kb/how-subscribe-news-feeds-and-blogs 

Are you on 115 or 128 so we can supply a new binary. Which platform?

**Comment by Betterbird** [comment] 2024-11-25 12:18
We'll do an updated build of 115 for Linux soon. It will be reported to Issue #368.
