### ISSUE TITLE
Boolean Filter Rules: Adding 2nd and 3rd level groups can cause open brackets (and thereby move 1st level rules to the 2nd level)

### ISSUE THREAD

**Issue by ThiloteE** [Betterbird/thunderbird-patches#62] opened 2022-06-10 15:13 UTC
Follow up to #35 and #60.

I did some tests using the linux build you sent me [here](https://github.com/Betterbird/thunderbird-patches/issues/60#issuecomment-1147668544) (91.10.0-bb33 (64-bit) and stumbled upon this.

How to reproduce:

1. 1st level match ALL + 2nd level match ANY + 3rd level match ALL:

https://user-images.githubusercontent.com/73715071/173094737-25bc9bd1-f1ef-4f63-a92b-cd3118262692.mp4

2. 1st level match ALL + 2nd level match ALL + 3rd level match ANY:

https://user-images.githubusercontent.com/73715071/173094766-9b79ab4a-7711-4c7f-8d70-5efa0f1b8d0f.mp4

**Comment by ThiloteE** [comment] 2022-06-10 15:14
A specific requirement seems to be adding the 3rd level group (I have not tested for 4th level and more levels), as the following two configurations now seem to be fixed and work well:

![grafik](https://user-images.githubusercontent.com/73715071/173095001-462ed137-64eb-49c5-ac79-321954cf9c1e.png)

![grafik](https://user-images.githubusercontent.com/73715071/173095822-44faf517-9ec8-4e6e-b433-f292d5143bdb.png)

**Comment by Betterbird** [comment] 2022-06-10 18:07
Thanks for the videos. Maybe in the future you can just report the bug with two images while making the window big enough to fit everything.

![image](https://user-images.githubusercontent.com/86832723/173125120-4550271e-0bd6-4c81-9492-af4c4216a622.png)
is incorrectly restored as
![image](https://user-images.githubusercontent.com/86832723/173125213-ca14e476-2cc2-48a3-baf3-3e492edc3081.png)

We can inspect the content of the msgFilterRules.dat file ourselves, or just paste the content here.

**Comment by Betterbird** [comment] 2022-06-10 19:35
We can reproduce the issue. The msgFilterRules.dat has the correct content:
```
condition="AND (subject,contains,a) AND [subject,contains,b) AND [subject,contains,c) AND (subject,contains,d] AND (subject,contains,e)"
```
The bracket at "d" closes two groups, that's by design. Remember that the condition tree is flattened into a list of terms and the terms carry a begin/end group. And obviously the flag can only be set once, even if two groups end on the term. In the debug it looks like this:
```
entry 0: and   level 1"
entry 1: and begin  level 2"
entry 2: and begin end level 3"
entry 3: and   level 1"
```
Sadly when this is restored, the "e" condition shifts from level 1 to level 2 since the double-end is not taken into account. The rule execution should still work as long as you don't edit the group again. This is a tricky one.

**Comment by Betterbird** [comment] 2022-06-10 21:29
We've detected another problem. If you construct
![image](https://user-images.githubusercontent.com/86832723/173152814-c337235e-f482-4e40-9786-00eba8122b06.png)

you get
```
condition="AND (subject,contains,a) AND [subject,contains,b] AND [subject,contains,c) AND (subject,contains,d) AND (subject,contains,e]"
```
which is missing a `]` at "d" and the `]`at "b" isn't right. This seems to depend on the creation order since we also saw:
```
condition="AND (subject,contains,a) AND [subject,contains,b) AND [subject,contains,c) AND (subject,contains,d) AND (subject,contains,e]"
```
what only the term for "d" isn't right.

**Comment by Betterbird** [comment] 2022-06-10 21:44
Looks like there is also an issue with something like:
![image](https://user-images.githubusercontent.com/86832723/173154667-2bac0c97-0b15-4c09-b98c-db89143a0abb.png)
That's [[[a] && b] && c]
Of course we can't store three "begin groups" in term "a". Looks like we'll have to change the data structure of the term to all storing how groups begin/end there.

**Comment by Betterbird** [comment] 2022-06-11 10:41
We're working on it. The design will be changed to balance the brackets, so
```
condition="AND (subject,contains,a) AND [subject,contains,b) AND [subject,contains,c) AND (subject,contains,d]] AND (subject,contains,e)"
```
Note the double bracket after "d". Expect a fix in the news few days.

**Comment by Betterbird** [comment] 2022-06-11 22:22
The following cases work now with the latest commit:
```
name="Ex3"
enabled="yes"
type="17"
action="Mark flagged"
condition="AND (subject,contains,a) AND [subject,contains,b) AND [subject,contains,c) AND [subject,contains,d]]]"
name="Ex1"
enabled="yes"
type="17"
action="Mark flagged"
condition="AND (subject,contains,a) AND [subject,contains,b) AND (subject,contains,) AND [subject,contains,c) AND (subject,contains,d]] AND (subject,contains,e)"
name="Ex2"
enabled="yes"
type="17"
action="Mark flagged"
condition="AND (subject,contains,a) AND [subject,contains,b) AND [subject,contains,c] AND (subject,contains,d] AND (subject,contains,e)"
```
The case from https://github.com/Betterbird/thunderbird-patches/issues/62#issuecomment-1152758362 doesn't work yet.

**Comment by Betterbird** [comment] 2022-06-12 08:02
@RealRaven2000: Please note that significant changes are being implemented here. Most prominently, we're changing `nsIMsgSearchTerm.beginsGrouping` and `nsIMsgSearchTerm.endsGrouping` from `bool` to `unsigned long` so we can store the number of groups starting and ending at a given term. You will remember the discussion we had privately about multiple groups terminating at a term leading to an `[ ]` imbalance. Now it's always balanced. We don't know whether your add-ons create search terms. If so, they'd need to be adjusted for work for BB.

**Comment by Betterbird** [comment] 2022-06-12 09:59
The latest commit also fixes this case where many groups begin at the same term:
```
condition="AND [[[[subject,contains,a] AND (subject,contains,b] AND (subject,contains,c] AND (subject,contains,d] AND (subject,contains,e)"
```

**Comment by RealRaven2000** [comment] 2022-06-12 11:01
> @RealRaven2000: Please note that significant changes are being implemented here. Most prominently, we're changing `nsIMsgSearchTerm.beginsGrouping` and `nsIMsgSearchTerm.endsGrouping` from `bool` to `unsigned long` so we can store the number of groups starting and ending at a given term. You will remember the discussion we had privately about multiple groups terminating at a term leading to an `[ ]` imbalance. Now it's always balanced. We don't know whether your add-ons create search terms. If so, they'd need to be adjusted for work for BB.

Thanks for the heads up. Indeed quickFilters **main business is creating filters** (so far I don't think I set beginsGrouping during filter generation, but it's definitely important for its backup / restore / copy / paste features). In a nutshell - the idea of the quickFilters assistant is auto-filling thinks like folder target or from address based on emails moved / tagged; so it needs intimate knowledge of the internals of a filter. Can I use "typeof beginsGrouping" to determine patch state?

**Comment by Betterbird** [comment] 2022-06-12 11:16
Well, if you don't create groups in quickFilters, then you wouldn't be setting {begins|ends}Grouping on the `nsIMsgSearchTerm`. No idea how you check the type on an attribute defined in an IDL. As discussed before, you can detect BB usage and then set the grouping members to true/false or 1/0 or higher numbers if you created more complex filters. See the `condition` examples mentioned earlier. Attached also a sample filter file what will work once an updated version of BB (91/102 beta) is released later today.
[msgFilterRules.dat.txt](https://github.com/Betterbird/thunderbird-patches/files/8885703/msgFilterRules.dat.txt)

**Comment by RealRaven2000** [comment] 2022-06-12 11:35
> Well, if you don't create groups in quickFilters, then you wouldn't be setting {begins|ends}Grouping on the `nsIMsgSearchTerm`. No idea how you check the type on an attribute defined in an IDL. As discussed before, you can detect BB usage and then set the grouping members to true/false or 1/0 or higher numbers if you created more complex filters. See the `condition` examples mentioned earlier. Attached also a sample filter file what will work once an updated version of BB (91/102 beta) is released later today. 

Thanks for the example! I will find a way to do this - even though my current filter templates don't create groups, users are allowed to generate their own templates and thus can add groupings.

Merging new rules into existing filters is going to be challenging, [this adds more search terms to existing filters and will need to detect the correct new position - e.g. at the end of a group with matching search conditions, such as "_from contains_" with `booleanAnd=false` - for the merged search terms and move parentheses (`endsGrouping`) to the last added term]. I will get the new beta as soon as it's available.

**Comment by Betterbird** [comment] 2022-06-12 18:39
@ThiloteE: The latest build at https://www.betterbird.eu/downloads/get.php?os=linux&lang=en-US&version=latest should fix the issues you reported and the ones I discovered myself. I discovered more issues: Deleting a term or group out of the middle of a complex expression do not (yet) adjust the counts of beginning/ending groups, so deletion in complex situation will likely cause invalid rules. We filed issue #63 for that.

**Closed by Betterbird** 2022-06-12 18:39 UTC

**Comment by ThiloteE** [comment] 2022-06-12 20:30
Thank you :-) I will do some testing eventually. In some days / weeks.

**Comment by ThiloteE** [comment] 2022-07-30 22:56
**Positive Feedback:**

I have now used BB 91.10 for ~ 6-7 weeks with some "simple" complex filter rules on my main machine and have **not** noticed any other bugs (apart from #63) so far. Hooray :)

Today I have finally made the jump to BB 91.12.0
I went through all my `filterrules.dat` files manually (via text editor) and changed the rules to adhere to the new filterrules syntax. :+1:

**Comment by Betterbird** [comment] 2022-07-31 07:06
Thanks for the feedback.
