### ISSUE TITLE
Wayland Icon

### ISSUE THREAD

**Issue by maximushugus** [Betterbird/thunderbird-patches#46] opened 2022-04-16 17:03 UTC
Hello and thanks for the work on Betterbird, which is awesome !
I use Arch Linux with KDE on Wayland.
It looks as if there is a bug with the icon of the app : 
When launching Betterbird, the icon on the taskbar is not the one it should be : instead, the Wayland icon appears.
And by pinning Betterbird to the taskbar, the app doesn't launch "on the pinned app" (see capture below).
![Screenshot_20220416_185910](https://user-images.githubusercontent.com/36080343/163684436-d514db18-aede-4d3b-8f8c-b3d16e7f6dc6.png)

Is there a way to change this behavior that is not present in Thunderbird ?

Thanks

**Comment by Betterbird** [comment] 2022-04-16 18:10
Hmm, neither do we use KDE nor Wayland. No idea what KDE does, looks OK on our various Mint installations:
![image](https://user-images.githubusercontent.com/86832723/163686401-99aa187d-c1d9-49c7-bee2-435e0433bbe0.png)

I believe the Thunderbird package on Arch is a special build, at least according to
https://thunderbird.topicbox.com/groups/beta/T48720341fd6912e6-M0bdf8a1b828b41376239e4c0
whereas BB is just the "regular" Linux build.

Maybe you can find Luna Jernberg somehow and ask. Looks like it's this person: @bittin.

**Comment by Betterbird** [comment] 2022-04-16 18:33
@posi81: Do you have any insights here?

**Comment by Posi81** [comment] 2022-04-16 19:46
@Betterbird @maximushugus I will check

**Comment by Posi81** [comment] 2022-04-16 19:55
At the moment i use on ARCH LINUX for some technical reasons X11.... but i switched fast to wayland.... for me looks normal...

![grafik](https://user-images.githubusercontent.com/59346176/163689523-fde2c09a-9d65-49ea-93aa-26c0a7897541.png)

Did you restart your Arch after installing BB ?

**Comment by maximushugus** [comment] 2022-04-16 20:32
@Posi81 I tried restarting but still have the same problem. Are you on KDE ?

**Comment by Posi81** [comment] 2022-04-16 21:08
@maximushugus yes i am. Can you check if the icons are correct installed?
`ls /usr/share/icons/hicolor/256x256/apps`

**Comment by maximushugus** [comment] 2022-04-16 21:14
In this directory I have a link for the BB icon.
I tried to put directly the file of the icon in the directory you said, but it doesn't change anything

**Comment by Posi81** [comment] 2022-04-16 21:16
can you try please...
`sudo gtk-update-icon-cache /usr/share/icons/*`

**Comment by maximushugus** [comment] 2022-04-16 22:19
This doesn't resolve the problem

**Comment by Posi81** [comment] 2022-04-19 18:56
I asked a few people in the community to take a look at the "issue".
As I suspected, the problem is NOT with the Betterbird package.
Everything works for me and the others fine if we start the KDE interface with KDE under Wayland instead of the X11 display server.
@maximushugus : The error must be in your own Wayland configuration.

**Comment by bittin** [comment] 2022-04-19 18:59
Sadly have an older GTX 760 GPU that does not do Wayland, so can't help out there

**Comment by Posi81** [comment] 2022-04-19 19:02
With wayland you haven't missed anything YET. ;-)

**Comment by Betterbird** [comment] 2022-04-19 19:17
> Sadly have an older NVIDIA GTX 760 GPU that does not do Wayland, only Xorg so can't help out there

@bittin: Could you please make the mozconfig available that you use to build TB for Arch Linux. Maybe there is an option we could try for BB.

**Comment by bittin** [comment] 2022-04-20 12:29
@Betterbird here it comes: https://pastebin.com/04SUZdeH

**Comment by Betterbird** [comment] 2022-04-20 13:45
Thanks, an interesting bunch of options you have there. We should probably copy the alsa/jack stuff although that might already be the default by now. According to https://www.thunderbird.net/en-US/thunderbird/91.0/system-requirements/, TB requires PulseAudio, I know there was a lot of discussion around the audio stuff. That said, I don't see anything particularly relating to Wayland. Am I missing something?

**Comment by Betterbird** [comment] 2022-05-11 21:06
Any update here? Can we close this?

**Comment by maximushugus** [comment] 2022-05-11 21:09
Sorry, I didn't have the time to reply.
For me the problem is still here in KDE Wayland. I tried reinstalling BB but this didn't solved the problem

**Comment by Betterbird** [comment] 2022-05-11 21:31
Well, at the other comments suggest, the problem doesn't appear to be in BB but in your Linux installation.

**Comment by mfschumann** [comment] 2022-09-28 16:40
@maximushugus If the problem persists and if you are open to using flatpak you could give the [Betterbird flatpak](https://flathub.org/apps/details/eu.betterbird.Betterbird)  a try.

**Comment by maximushugus** [comment] 2022-09-28 16:50
> @maximushugus If the problem persists and if you are open to using flatpak you could give the [Betterbird flatpak](https://flathub.org/apps/details/eu.betterbird.Betterbird) a try.

The problem solved very recently, this week, maybe after an update. I still don't know why it happened but it's solved. Thanks

**Closed** 2022-09-28 16:51 UTC
Labels: Not Reproducible
