### ISSUE TITLE
OpenPGP repair not working in BB 91.6.0, but does work in TB 91.6.0

### ISSUE THREAD

**Issue by tibitts** [Betterbird/thunderbird-patches#29] opened 2022-02-09 16:30 UTC
I'm sending a PGP/MIME encrypted message via the corporate Exchange server using TB 91.5.1. Access to the Exchange server is via EWS using the Owl add-on. The message is sent successfully. 

However, somehow the Exchange server is screwing up the encrypted message. On the receiving end (this is just an ordinary IMAP account), I'm opening the message with TB 91.5.1. Due to the Exchange screw-up the message cannot be decrypted right away, instead TB prompts to repair the message with a 'Repair' button in the header pane to fix the Exchange screw-up. After pressing 'Repair' the message is reloaded, and then successfully decrypted, the signature is valid. All good using Thunderbird.

When attempting to open the repaired message using BB 91.6.0 it just shows a message with an empty body, and there is no indication that it actually is an encrypted message, i.e. there is no OpenPGP button in the header pane.
The BB error console shows this:
Error: Failed to decode base64 string! [data.jsm:48:12](chrome://openpgp/content/modules/data.jsm)
    decodeBase64 chrome://openpgp/content/modules/data.jsm:48
    onStopRequest chrome://openpgp/content/modules/mimeDecrypt.jsm:513
    onStopRequest self-hosted:1175

This is exactly reproducible with two different messages. BB 91.6.0 also did not prompt for repair of the original message received.
After repair done with TB91.5.1 the message can also be open just fine using TB91.6.0. But again, it could neither be repaired nor opened after repair using BB 91.6.0.

**Comment by Betterbird** [comment] 2022-02-09 17:48
Thanks for the report. Looks like a regression from the search in encrypted messages shipped in 91.2.1-bb17. Is the issue present in 91.2.0-bb16? You can get the old versions from https://www.betterbird.eu/downloads/ - WindowsInstaller / Previous.

Would you be willing to try a special version of our latest build 91.6.0-bb26 to narrow down the issue? We could make this available in the coming days. Overall, we'll endeavour to get this fixed as soon as possible.

I would also be good to receive a test message from you that is equally damaged by your server. Attached the key to use.
[pubkey.asc.txt](https://github.com/Betterbird/thunderbird-patches/files/8034994/pubkey.asc.txt)

**Comment by tibitts** [comment] 2022-02-09 18:31
> Is the issue present in 91.2.0-bb16?

No, that version works fine.

> Would you be willing to try a special version of our latest build 91.6.0-bb26 to narrow down the issue?

I'd be happy to do that. A Linux version would be preferred.

**Comment by tibitts** [comment] 2022-02-09 19:27
> I would also be good to receive a test message from you that is equally damaged by your server.

A test message is coming your way.

**Comment by Betterbird** [comment] 2022-02-10 13:07
Thanks, we have all the material we need and can reproduce the bug. Strangely, TB 91.6.0 displays **four** notifications offering to repair the corrupted message. Do you see that as well and has that been reported? BB displays the same for notifications but repair fails with a console error. We'll look into it.

**Comment by tibitts** [comment] 2022-02-10 16:37
> TB 91.6.0 displays **four** notifications offering to repair the corrupted message. Do you see that as well and has that been reported?

Just for the record, I never seen more than one prompt with TB, and either one prompt or none at all with BB.

**Comment by Betterbird** [comment] 2022-02-10 22:34
Fixed by two commits. "Latest build" release will be available for Windows within 60 minutes. Check the release notes.

Thanks for reporting!

**Closed by Betterbird** 2022-02-10 22:34 UTC
