### ISSUE TITLE
Attachment save-dialog troubled with some characters on Linux

### ISSUE THREAD

**Issue by bravequickcleverfibreyarn** [Betterbird/thunderbird-patches#58] opened 2022-05-11 18:56 UTC
When attachment name contains some characters (Guess for non-ASCII) save dialog get into trouble.

Thunderbird does not exhibit this — different dialog there.

![Unsupported Chars](https://user-images.githubusercontent.com/26486200/167924969-e24f8525-4204-41ed-aa89-d328a794a2cb.png)

**Comment by Betterbird** [comment] 2022-05-11 19:31
Can you please supply a test case. You can forward the message with the attachment as attachment (yes, forward the message as attachment). Opening attachments has been a terrible mess all through the 91 cycle, BB advanced many patches and fixed things, at the moment I can think of one area where BB and TB differ.

**Comment by Betterbird** [comment] 2022-05-11 19:39
We had a look, https://bugzilla.mozilla.org/show_bug.cgi?id=1755592 is fixed in BB 91 but not TB 91, that means, TB doesn't pre-fill the file name. So if the file name isn't good for saving, why don't you supply a "good" one. Anyway, we're still interested in the sample that reproduces the issue.

**Comment by bravequickcleverfibreyarn** [comment] 2022-05-11 20:31
[Sample.tar.gz](https://github.com/Betterbird/thunderbird-patches/files/8673230/Sample.tar.gz)

Steps

1. Extract message from archive and open it in Betterbird (File|Open|Saved Message).
2. Try to save message either by:
- right click on file
- menu 
![Screenshot_20220511_222248](https://user-images.githubusercontent.com/26486200/167941678-59a4deef-738f-4593-8634-a366bc2d3713.png)

_Save All_ dialog path work fine (no prefill)

**Comment by Betterbird** [comment] 2022-05-11 20:50
Thanks for the sample. Works just fine on Windows in BB 91.9.0-bb31. Let's try on Linux now.

**Comment by Betterbird** [comment] 2022-05-11 21:03
On Linux Mint, this looks rather bad, not even the filename is shown correctly:
![image](https://user-images.githubusercontent.com/86832723/167946127-e6a6a660-8b60-481b-9fde-3f26f00a4848.png)
But the file is saved on the desktop with the strange name:
![image](https://user-images.githubusercontent.com/86832723/167946437-422d4b7c-3908-4c5e-8640-84454790b658.png)

I don't think we can fix anything here, seems like an issue on Linux.

@posi81, how is this working for you?

**Comment by Betterbird** [comment] 2022-05-11 22:19
@bravequickcleverfibreyarn, what are the specs of your Linux?

**Comment by Posi81** [comment] 2022-05-17 17:43
Oh... i have the same 
![image](https://user-images.githubusercontent.com/59346176/168876790-81d35448-9c9d-4a2c-8c6e-c76542da83aa.png)

**Comment by Betterbird** [comment] 2023-02-16 14:56
Is this still an issue? No one on the team could reproduce.

**Closed by Betterbird** 2023-02-16 14:56 UTC
Labels: Not Reproducible

**Comment by bravequickcleverfibreyarn** [comment] 2023-02-16 17:07
I cannooy tell, I am not using Betterbird these days (not installed even). I suppose it is fixed for everybody.

**Comment by k-nard** [comment] 2024-01-11 08:58
Hi,

I have also the same issue on Betterbird.
Installed via flatpak on openSUSE 15.5.
The "invalide" popup comes up each time there is special char in attachment.

**Comment by k-nard** [comment] 2024-01-11 09:08
I tried with binaries downloaded directly from betterbird website. No issue.
I will check with flatpak on other linux distro.

**Comment by Betterbird** [comment] 2024-01-11 09:34
What's different in FlatPak? @mfschumann?

**Comment by mfschumann** [comment] 2024-01-13 19:55
I cannot reproduce the issue on a fresh install of openSuse Leap 15.5 with KDE and BB 115.6.1-bb22 installed as flatpak. The characters are messed up both in Betterbird and in the "Save As" dialog, but the file is saved successfully.

![image](https://github.com/Betterbird/thunderbird-patches/assets/9102962/37ef787c-3a38-4a23-be03-ac87da5fb3fb)

**Comment by Betterbird** [comment] 2024-01-13 20:41
Thanks for testing.

The Betterbird team won't action this ticket. Multiply the number of distributions by the number of desktops times two for with/without Wayland times two for with/without FlatPak and you have a complete support disaster. Besides, there is zero code for font handling or file open/save dialogue boxes in TB or BB. All this code is supplied by the OS/desktop or the Mozilla platform.

If you want to take the issue further, at first, try to save a webpage or downloaded file with Firefox. If that doesn't work, file a bug for Firefox. Otherwise, try with the TB FlatPak and see whether it works. If not, file a bug with them. If only BB FlatPak doesn't work, a ticket should be filed for BB FlatPak, not BB itself.
