### ISSUE TITLE
Can't move an email into a Gmail folder: it automatically comes back to inbox

### ISSUE THREAD

**Issue by Ph15** [Betterbird/thunderbird-patches#326] opened 2024-07-19 11:51 UTC
Steps to reproduce:

Hi there!

Thanks for all the work you do to make Betterbird a better alternative to Thunderbird. It's appreciated!
I am facing a recurring and annoying bug, which also appears on Thunderbird. I posted it on Bugzilla under the [bug report n°1908872](https://bugzilla.mozilla.org/show_bug.cgi?id=1908872).

**Steps to reproduce:**
I am willing to move an email to a Gmail folder from my inbox.
So basically righ-click on the email, move to, and choose my destination folder.

**Actual results:**

The email disappears for two seconds, then reappears again in my inbox, as my move to command had not been taken into account.
P.S.: This happen only on my Gmail account, not my other email providers. And it seems to happen mostly with newly created folders (via gmail.com).

**Expected results:**

The email should have been properly moved to the folder.
P.S.: On Gmail's web app and my mobile app, everything is running well.

Thanks for caring!

**Comment by Betterbird** [comment] 2024-07-19 19:43
We don't quite understand this report. You found an issue with Thunderbird which also exists in Betterbird. So you filed a Thunderbird bug today. Obviously you won't get an immediate reaction there. And then, although the bug is upstream, you come to us and ask us to fix it? Is that the correct understanding? Obviously that won't happen, since there are 15.000+ TB bugs which we won't fix in a flash.

Your problem appears to be very specific to your setup. I can move a message on Gmail to a folder and it remains there, so for starters, the bug is not easily reproducible. Set up a new profile and see whether the problem exists there, preferably on an account where no other client is interfering.

The next question is of course whether there are any filters at play.

Overall, if we decide to look into this further, it would best be done in the upstream ticket.

**Closed by Betterbird** 2024-07-19 19:43 UTC

**Comment by Ph15** [comment] 2024-07-24 13:12
Hello!
I'm sorry if I have posted this in the wrong place. I didn't mean to bother you or push something onto you.
I thought it was more appropriate to post it on both channels in case it was an unsolvable TB bug, and thinking you were more agile to solve this type of bugs.

I don't know why this bug occurs either. I have no filters at play. All my other inboxes work just fine... Same on my phone. So I'll try setting up another client as you say, and see if it helps with anything.
Kind regards,
— Phil

**Comment by Betterbird** [comment] 2024-07-24 13:18
The TB person Gene who has already commented is the right person to look at it. However, neither he nor me can reproduce. He suggested to run IMAP logging to see what's going on.

**Comment by Ph15** [comment] 2024-07-31 13:30
Sounds good, I'll follow up with him. Thank you!l

**Comment by Betterbird** [comment] 2024-07-31 18:33
I'm observing this ticked, you've done everything possible to start with a clean slate. You will really need IMAP logging to see what's happening.
