### ISSUE TITLE
Major slow application launch

### ISSUE THREAD

**Issue by securegh** [Betterbird/thunderbird-patches#243] opened 2023-12-29 15:38 UTC
Hello, 

Thank you for making this alternative to Thunderbird. 
I just installed the flatpak version and it's extremely slow to start like up to a minute. 
Compared to Thunderbird native app (non flatpak)  which start in a second. 
Is this normal behavior and how can I fix this? 

Thank you!

**Comment by Betterbird** [comment] 2023-12-29 16:04
What you write is hard to believe given that there are only a few differences between TB and BB when it comes to startup, nothing that would explain a difference between one second and one minute.

If one is FlatPak and one is native, you're likely not running it on the same profile, so we're comparing apples with pears. Besides, FlatPak uses a sandboxed profile, so how do we know that that's not a contributing factor here? CC'ing @mfschumann the FlatPak maintainer here. 

One thing that is different is the way mail and folder tabs are restored at startup. Basically the restauration of those tabs is broken in version 115 "Supernova-kaboom", so at times TB restores tabs empty. We implemented a mitigation which restores all the tabs correctly but sequentially, but which therefore delays startup.

So three suggestions:
1. Download "navite" BB via the .tar.bz2 on our site and start `betterbird -p` to run on the TB profile.
2. Close all folder and mail tabs, or use this option:
![image](https://github.com/Betterbird/thunderbird-patches/assets/86832723/51f92865-e304-4cbb-a192-162d14121750)
Select the second or third option.
3. Run startup profiling, save the profile locally and make it available to us. See https://profiler.firefox.com/docs/#/./guide-startup-shutdown. Basically start from the command line with `MOZ_PROFILER_STARTUP=1` set. Once started, go to "Tools > Developer Tools > Developer Toolbox`, Performance tab, stop the profiling which got started when you launched. There is UI to save or submit the profile, please save it and don't submit it to Mozilla.

Altogether this appears like a support of troubleshooting ticket, not a bug report, so I'm closing it. We can continue to communicate here or via our support e-mail.

**Closed by Betterbird** 2023-12-29 16:04 UTC

**Comment by Betterbird** [comment] 2024-01-04 16:56
Any updates on this?

**Comment by securegh** [comment] 2024-03-31 07:16
> Any updates on this?

Thank you for your detailed reply!
I haven't retested the flatpak version of BB yet.
I tested the native BB tar.bz2 executable and it's as fast and better then vanilla TB.
One feature I like about Betterbird is minimize to system tray, is there a way to start up BB minimized in system tray?  

Thank you again!

**Comment by Betterbird** [comment] 2024-03-31 09:58
> is there a way to start up BB minimized in system tray?

See https://www.betterbird.eu/expert-tips/

Relevant preferences: Start minimized: `mail.startupMinimized` (no UI)
