### ISSUE TITLE
[v115] ja locale update

### ISSUE THREAD

**Issue by kiki-ja** [Betterbird/thunderbird-patches#195] opened 2023-09-03 13:00 UTC
I have translated "Show tab bar vertically" into Japanese.
Attached is the ja.cmd and preferences.ftl.

[115_ja.cmd_preferenses.ftl.zip](https://github.com/Betterbird/thunderbird-patches/files/12506070/115_ja.cmd_preferenses.ftl.zip)

Thanks.

**Comment by Betterbird** [comment] 2023-09-03 13:04
Thanks, it's already committed: https://github.com/Betterbird/thunderbird-patches/commit/bf7256f96969851d01254c531e5d238e8b009c54

**Closed by Betterbird** 2023-09-03 13:04 UTC

**Comment by kiki-ja** [comment] 2023-09-03 13:18
I have confirmed that it has already been committed.
I hope you will leave it open and not close it, as I may update the locale file in the future.

Thanks.

**Comment by Betterbird** [comment] 2023-09-03 13:23
Well, I closed the issue since there is nothing to action here at the moment. Feel free to reopen it if more work arises. Anyway, all notifications reach us, irrespective of whether the issue is open or closed. Thanks again for your help.

**Comment by kiki-ja** [comment] 2023-12-06 08:16
I have updated the translations of new strings in menubar.ftl and preferences.ftl for Betterbird 115.5.1.
The files are attached.

[ja_menubar_preferences.zip](https://github.com/Betterbird/thunderbird-patches/files/13578324/ja_menubar_preferences.zip)

Thanks.

**Comment by kiki-ja** [comment] 2024-03-02 04:09
Hi Jörg,

I am sending you the ja.cmd with the added translation into Japanese.
It appears to be a function to edit the header, but since i cannot see the actual dialog, i may send you a correction at a later date.

[ja_cmd.zip](https://github.com/Betterbird/thunderbird-patches/files/14468028/ja_cmd.zip)

**Comment by kiki-ja** [comment] 2024-03-17 13:18
Hi Jörg,

I am sending you the ja.cmd for Betterbird 115.9.0 as an attachment.

[ja115.9.0cmd.zip](https://github.com/Betterbird/thunderbird-patches/files/14627495/ja115.9.0cmd.zip)

Thanks.

@kiki-ja

**Comment by kiki-ja** [comment] 2024-03-18 02:43
Hi Jörg,

I send you the ja.cmd of the Betterbird 115.9.0 revise as an attachment.

[ja115.9.0cmd.zip](https://github.com/Betterbird/thunderbird-patches/files/14630277/ja115.9.0cmd.zip)

Thanks.

@kiki-ja
