### ISSUE TITLE
Flexible spaces disappear from Unified Toolbar after switching to 'default toolbar' tabs

### ISSUE THREAD

**Issue by dillenger** [Betterbird/thunderbird-patches#194] opened 2023-09-02 23:41 UTC
Flexible spaces disappear from the Unified Toolbar after switching to some tabs, all buttons then align at the end.
Tabs where this happens include add-on tabs like ThirdStats and uBlock Origin and the Troubleshooting Information tab.
Apparently these tabs do not have their own Unified Toolbar Space, they only show the default space.

**Comment by Betterbird** [comment] 2023-09-03 07:12
And that doesn't happen in TB? Have you filed an upstream bug?

**Comment by dillenger** [comment] 2023-09-03 10:15
Betterbird only, if it happened in Thunderbird I would have filed a bug there.

**Comment by Betterbird** [comment] 2023-09-03 11:17
Can you please post some screenshots. We're not aware of any code changing the behaviour of the unified toolbar, well, apart from moving it under the menu bar. We also have some tab restoration changes, but that shouldn't affect the toolbar.

**Comment by dillenger** [comment] 2023-09-03 11:53
Ok 4 screenshots with all addons except uBlock Origin & Profile Switcher disabled.
Flexible spaces are not completely gone but definitely smaller and everything is aligned at the end of the toolbar.
Customize Toolbar:
![Screenshot 2023-09-03 133117 - customize](https://github.com/Betterbird/thunderbird-patches/assets/571067/7ca6e267-f396-4a18-87a1-d49f2011f8fa)
Buttons OK:
![Screenshot 2023-09-03 133203 - buttons ok](https://github.com/Betterbird/thunderbird-patches/assets/571067/a9cddd64-7e97-42d4-b158-aefb58f03cb2)
uBlock Dashboard:
![Screenshot 2023-09-03 133259 - ublock dashboard](https://github.com/Betterbird/thunderbird-patches/assets/571067/671dafd4-f6ec-415e-afa1-7ec76c7d1548)
Buttons moved to end:
![Screenshot 2023-09-03 133455 - buttons moved to end](https://github.com/Betterbird/thunderbird-patches/assets/571067/93f4f231-d625-4b8a-abe8-af94fa99a097)

**Comment by Betterbird** [comment] 2023-09-03 12:32
This will be difficult to fix since it doesn't reproduce here:

![image](https://github.com/Betterbird/thunderbird-patches/assets/86832723/94c7df71-3e5d-4fbe-8adb-ee59e5bb44e8)
![image](https://github.com/Betterbird/thunderbird-patches/assets/86832723/58acbf03-d282-488e-acb6-1d427ef0f8e9)
![image](https://github.com/Betterbird/thunderbird-patches/assets/86832723/ecc94d40-be13-4ec6-b8d8-74b35ee8be16)
![image](https://github.com/Betterbird/thunderbird-patches/assets/86832723/da882093-6f44-4761-88d9-51728868114c)

You can see that the first and last picture are the same.

So what is the minimal configuration to reproduce this on a new profile, preferably without using any add-on? We're also not convinced that this isn't a TB issue since we've surely haven't changed any code to render the unified toolbar, at least not deliberately.

What happens after a restart? Does it become good again?

**Comment by dillenger** [comment] 2023-09-03 12:39
I will try a fresh profile, it is ok after restart and after changing anything in Customize Toolbars.

**Comment by dillenger** [comment] 2023-09-03 14:39
Also happens with a fresh profile, no add-ons.
Customize toolbar, remove the search box and add Get Messages and Write buttons to the start of the toolbar.
Now open Help > Troubleshooting Information.
Go back to the previous tab, the buttons have moved to the right.
This doesn't happen on Thunderbird.

**Comment by dillenger** [comment] 2023-09-03 15:18
Apparently a hidden search-bar item is added which pushes the rest to the end:

![image](https://github.com/Betterbird/thunderbird-patches/assets/571067/db5d218b-a036-474c-a015-1119c4207d25)

**Comment by Betterbird** [comment] 2023-09-03 20:58
Thanks, we can see it now. The search item is there in TB:
![image](https://github.com/Betterbird/thunderbird-patches/assets/86832723/79d23077-d80d-497a-8964-53ebb2aa47b3)
It has hidden="" but it his hidden.

In BB it looks the same:
![image](https://github.com/Betterbird/thunderbird-patches/assets/86832723/0366df47-0433-4e68-9b9b-6dddbd95077b)

We can't detect any difference, however, the thing is only semi-hidden, still occupying the allocated space.

**Comment by Betterbird** [comment] 2023-09-03 21:18
It's this CSS:
![image](https://github.com/Betterbird/thunderbird-patches/assets/86832723/2d8f2dc8-9095-48de-96a3-4a11f1eddb57)

Taking `disiplay: list-item` removes it from the space calculation.

**Comment by Betterbird** [comment] 2023-09-03 21:21
Found it:
.\features\22-feature-vertical-tabs.patch:+  display: list-item;

**Comment by Betterbird** [comment] 2023-09-04 19:47
Fixed with commit references above. Included in this build:
https://www.betterbird.eu/downloads/115-Preview/betterbird-115.2.0-bb10-latest-build4.en-US.win64.installer.exe

**Closed by Betterbird** 2023-09-04 19:47 UTC

**Comment by dillenger** [comment] 2023-09-05 18:30
It's fixed, thanks.
