### ISSUE TITLE
Crash after waking up PC from sleep - related to Gnome?

### ISSUE THREAD

**Issue by DeN-AlB** [Betterbird/thunderbird-patches#235] opened 2023-12-14 17:29 UTC
Betterbird: 115.5.2-bb20 (64-Bit)
OS: Fedora 39 Workstation (Gnome)

Yesterday, I updated flatpak version of Betterbird to 115.5.2-bb20 (64-Bit). Since then, I got 2 crashes already when waking up PC from sleep with Betterbird minimized in taskbar.

Here's the log. Maybe it helps to find the issue.

[ccpp-2023-12-14-17:56:16.280692-15539.zip](https://github.com/Betterbird/thunderbird-patches/files/13676393/ccpp-2023-12-14-17.56.16.280692-15539.zip)

I left away the coredump-file, because it's too big for uploading.

**Comment by Betterbird** [comment] 2023-12-14 17:53
We had a similar support case the other day: "Crash after a few hours of use", that was reported for Fedora 38. The answer of the FlatPak maintainer @mfs was:

for debugging you can install the eu.betterbird.Betterbird.Debug flatpak and then follow this guide to run Betterbird under gdb:
https://blogs.gnome.org/mclasen/2017/01/20/debugging-a-flatpak-application/
There is no need to build the app yourself.
Some more thoughts:
Is it always a few hours until the crash or does the crash correlate to some event like receiving new mail?
When did you start having this issue? Is there a version of the flatpak that has worked fine?

**Comment by DeN-AlB** [comment] 2023-12-14 18:11
> Is it always a few hours until the crash or does the crash correlate to some event like receiving new mail?
I sent my PC to sleep for some hours. And after waking up with BB minimized in tray, the issue occurs. Yes, when waking up from sleep BB is getting new emails.

> When did you start having this issue? Is there a version of the flatpak that has worked fine?
Yesterday, after updating flatpak version to 115.5.2-bb20 (64-Bit). With version 115.5.1-bb19 (64-Bit) this issue wasn't there.

**Comment by DeN-AlB** [comment] 2023-12-18 18:55
Still getting these crashes. Sometimes they appear without sending the PC to sleep. I click on an email, Betterbird freezes and then crashes.

Am I the only one getting these crashes? :/

**Comment by Betterbird** [comment] 2023-12-19 01:40
> Am I the only one getting these crashes? :/

Hard to say. There are not a lot of reports about crashes. The support case mentioned earlier on and Issue #153.

**Comment by DeN-AlB** [comment] 2023-12-19 09:39
Maybe it's a TB-thing and not an BB issue. Let's wait for the next release and hopefully my crashes are gone then ... ;)

**Comment by Betterbird** [comment] 2023-12-19 10:15
I'm pretty sure we didn't change anything that would cause those crashes, or maybe the system tray integration. You could try switching that off:

Relevant preferences:
    System tray: mail.biff.show_tray_icon (has UI)
    System tray always: mail.biff.show_tray_icon_always (no UI)
    Minimize to tray: mail.minimizeToTray (has UI)
    Linux only: mail.minimizeToTray.supportedDesktops ("kde,gnome,xfce,mate") and mail.minimizeToTray.desktopsGtkWindowPresentWithTime (special activation, "mate") (no UI)
    Start minimized: mail.startupMinimized (no UI)
    Show new count: mail.biff.use_new_count_in_badge (has UI)
    Only count unread message in inboxes: mail.notification.count.inbox_only (no UI)

Clear the first two prefs.

**Comment by DeN-AlB** [comment] 2023-12-19 13:27
I'm using `mail.minimizeToTray` and `mail.biff.show_tray_icon_always`. Both I set to their default of `false` now.

Let's see if this helps ...

**Comment by Betterbird** [comment] 2023-12-19 13:30
Yes, make sure that the system tray icon doesn't show at all. That's really the only difference to TB that I can think of that could cause an issue. If it still crashes after a while, please switch to TB and check whether that crashes, too.

BTW, debugging instruction are in the second comment.

**Comment by DeN-AlB** [comment] 2023-12-19 13:35
> Yes, make sure that the system tray icon doesn't show at all.

There isn't a system tray icon anymore. But I'll minimize BB into the dash now.

**Comment by DeN-AlB** [comment] 2023-12-21 17:25
No crash since disabling the tray icon. There is only a tray icon, when I got new email.

Maybe the tray icon is the reason?

**Comment by Betterbird** [comment] 2023-12-21 17:28
Looks like it, doesn't it? You can leave the machine sitting there with an unread mail and when you come back, see whether it crashes.

**Comment by DeN-AlB** [comment] 2023-12-21 17:30
I already did so. Was away from the PC and when I came back there were new emails and the tray icon available.

**Comment by Betterbird** [comment] 2023-12-21 17:31
But the original comment talked about "sleep". So did it sleep in this case?

**Comment by DeN-AlB** [comment] 2023-12-21 17:33
There were situations where the PC was sleeping. When waking up the PC there wasn't any crash.

But let me test further. Will see in the next days ... ;-)

**Comment by DeN-AlB** [comment] 2023-12-21 20:31
I shouldn't have written that. BB was minimized into the dash. Then an email arrived and I saw the tray icon appearing. Bam ... BB was crashed. I had to restart BB again.

It looks like that the tray icon could be the reason for my crashes ...

**Comment by Betterbird** [comment] 2023-12-21 21:03
Can you run it in the debugger to find out where it crashes?

**Comment by DeN-AlB** [comment] 2023-12-22 21:34
I don't know how to do it ... What do I have to do?

**Comment by Betterbird** [comment] 2023-12-22 21:35
See the second comment above.

**Comment by DeN-AlB** [comment] 2023-12-22 21:38
Looks a bit complicated ... I'll try in the next days if I get it to run.

**Comment by icolquhoun** [comment] 2024-01-04 20:10
I have been experiencing this too for at least the last 2 flatpak releases. I don't let my machine sleep, but I do lock the screen when I walk away. Everytime after returning from a screenlock, whenever new mail arrived, Betterbird would crash.
I've disabled the tray icon and tested a lock followed by new mail arriving and so far, it seems like it isn't going to crash. I'm hoping that that's cured the problem. I'll update if it hasn't.

**Comment by Betterbird** [comment] 2024-01-04 20:47
Only the FlatPak crashes or also the .tar.bz2? Which desktop (as in KDE, Gnome, Xfce, Mate, etc.) are you using?

**Comment by icolquhoun** [comment] 2024-01-04 21:28
I haven't tried anything but the FlatPak. I'm on Pop!_OS (pretty much Gnome).

**Comment by DeN-AlB** [comment] 2024-01-05 07:43
Sorry for the delay, but I was a bit busy in the last days ...

For me, the issue is solved. I switched from Gnome to KDE and since then there wasn't any crash. I think this is an issue on Gnome. There isn't a system tray with tray icons, and you only get one if you are using an extension. Maybe this could be the reason.

Also, I used a Gnome patch to get Adaptive Sync that isn't available out of the box and as I read on Nobara website, this implementation could break the system tray.

https://nobaraproject.org/2023/12/26/december-26-2023/
> VRR (Variable Refresh Rate/Freesync) functionality. Gnome currently still requires patched-in VRR functionality. The pending MR has been waiting 3 years, and even doing so still breaks the system tray.

**Comment by janmechtel** [comment] 2024-01-06 16:43
I also have crashes "sometimes" with new emails on Fedora Gnome Wayland. I'll observe whether it's related to locking + experiment with the tray icon.

**Comment by Neriderc** [comment] 2024-01-08 04:07
Just checking in to say I also have had many crashes during sleep over the past few weeks or more. Also using the flatpak installed via the gnome software centre on Fedora 38. I will experiment with the system tray.

**Comment by janmechtel** [comment] 2024-01-08 09:43
I've disabled the tray icon but just had another crash, not sure if there is any useful info in the crash details:
![image](https://github.com/Betterbird/thunderbird-patches/assets/1004314/ea3ea7b7-68b4-4728-b076-6ff8c262cae9)

**Comment by Betterbird** [comment] 2024-01-08 09:53
Please keep in mind that TB and FF have crashes that BB inherited. If the crashes persist, you should see whether they can be reproduced on TB and then submit a crash report.

I'm under the impression that Wayland isn't even supported yet, since there are:
https://bugzilla.mozilla.org/show_bug.cgi?id=635134
https://bugzilla.mozilla.org/show_bug.cgi?id=1542587

**Comment by DeN-AlB** [comment] 2024-01-08 10:10
> I'm under the impression that Wayland isn't even supported yet

Just want to say that I'm on KDE Wayland at the moment. No crashes since I use that desktop environment. Although, tray icon is enabled completely.

**Comment by Betterbird** [comment] 2024-02-08 13:51
I'm closing this in favour for Issue #266. It's pretty clear that this is triggered by Gnome + Wayland.

**Closed by Betterbird** 2024-02-08 13:51 UTC

**Comment by Betterbird** [comment] 2024-02-24 15:23
Should be fixed in 115.8.0-bb24.
